services:

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
